<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2018
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
/**
 * Errors
 */
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['unzip_error'] 				= 'Extraction of file %s failed';
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['zip_content_error'] 			= 'Mandatory content (%s) not found in extraction folder';
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['sql_not_found'] 				= 'SQL installation template not found';
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['session_lost'] 				= 'The license session is timed out. Please restart the installation.';
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['version_conflict'] 			= 'Please use one of Contaos LTS versions: 4.13 or 5.3';
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['memory_limit']				= 'Memory Limit (memory_limit) too low (%s). Min.: 512M';
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['client_version_conflict'] 	= 'A newer version of the Theme Updater is available. Please update the module.';		
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['theme_compatiblity_conflict'] 	= 'Your current theme version %s is not compatible to Contao %s. Please run the update in Contao %s and update Contao afterwards.';		
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['theme_version_conflict'] 	= 'Contao %s is not supported. Supported Contao versions: %s';
