<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2018 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
/**
 * Errors
 */
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['label_key'] 			= 'License key / Order number';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['label_email'] 			= 'Order email address';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['submit_license'] 		= 'Request license';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['submit_install'] 		= 'Start update';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['sql_template_info'] 	= 'SQL template file: %s';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['input_email'][0] 		= 'Order email address';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['input_email'][1] 		= 'Enter the email address of your customer account.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['input_license'][0] 	= 'License key / Order number (Theme Updater)';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['input_license'][1] 	= 'You can find the order number on your invoice or in your customer account.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['input_license_theme'][0] 	= 'Order number (EclipseX or EclipseX + CustomCatalog Bundle)';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['input_license_theme'][1] 	= 'You can find the order number on your invoice or in your customer account.';

$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['label_status']		= 'Status: %s';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['label_step']			= 'Step: %s';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['button_reset'][0]		= 'Reset'; // linktext
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['button_reset'][1]		= 'Resets the theme license information and restarts the update process.'; // title
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['domainRegistrationError'] = '
The domain registered in the customer area for the theme license differs from the domain <span style="font-weight:bold">%s</span>.<br><br>Please update your license domain (Order number <span style="font-weight:bold">%s</span>) in your <a href="https://login.premium-contao-themes.com/" target="_blank" style="text-decoration:underline;">customer area</a>.<br>
You can find the license terms and answers to frequently asked questions (FAQ) <a href="https://www.premium-contao-themes.com/lizenzbestimmungen.html" target="_blank" style="text-decoration:underline;">here</a>.<br><br>
Once the update routine begins, the request from the domain (%s) will be saved in our system.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['sql_template_headline']				= 'Ready to import the demo website.'; // title
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['sql_template_subheadline']			= 'Note: Existing data will be lost. Your user profile will remain intact.'; // title
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['sql_template_info']					= 'The import of the demo website (SQL template) '; // title
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['button_sql_template_import']			= 'Execute import'; // title
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['choose_product_info']					= 'Please choose the product to install.'; // title
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['product_select_blankOption']			= 'Choose product...'; // title
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['button_systemlog'][0] 				= 'Go to system log...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['welcome_info'] 						= 'Enter your order number and order email address from your EclipseX / EclipseX + CustomCatalog order and click "Request license". After verifying your license information, you will be redirected.';		
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['sql_template_import_info'] 			= 'The SQL import may take a few minutes. After a successful import, you will be redirected to the Contao login.';		
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['access_denied'] 					= 'Message: %s';		
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['errors'] 							= 'Error: %s';		
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['not_supported'] 					= 'The updater supports the following products: %s';		
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['button_installer_buy'] 			= 'Contao Installer';		
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['enter_updater_license_info'] 		= 'Enter your order number for the theme updater order and click on "Request license".<br>After verifying your license information, you will be redirected, and you can start the 1-Click-Updater.<br>The theme data will automatically be downloaded from the Premium Contao Themes server to your server and then installed.';		
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['enter_theme_license_info'] 		= 'Enter your theme order number.';		
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['button_license_buy'] 				= 'Buy Theme Updater License';		
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['manual_table']['head']['task']		= 'Task';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['manual_table']['head']['description'] = 'Description';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['manual_table']['head']['status']		= 'Completed';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['manual_table']['head']['iframe']		= 'Documentation';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['submit_commit']						= 'Save progress';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['submit_done']							= 'Complete update';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['empty_tasks']							= 'No further tasks.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['up_to_date'] 							= 'No new version available';		


/**
 * Breadcrumb
 */
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['welcome'][0] 							= 'Start';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['welcome'][1] 							= 'Everything starts here';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['validation'][0]							= 'License query';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['validation'][1] 						= "Your license is being verified.";
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['accepted'][0] 							= 'License valid';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['accepted'][1] 							= 'Your license has been validated.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['not_accepted'][0] 						= 'License not valid';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['not_accepted'][1] 						= 'Your license could not be validated.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['loading'][0] 							= 'Loading data';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['loading'][1] 							= 'The data is being loaded';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['installation.unzip'][0] 				= 'Unzipping data';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['installation.unzip'][1]					= 'The data is being unzipped'; 
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['installation.copy_files'][0] 			= 'Copying data';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['installation.copy_files'][1] 			= 'The data is being distributed to your target directories.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['installation.clear_cache'][0] 			= 'Clear prod. cache';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['installation.clear_cache'][1] 			= 'Clear prod. cache.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['installation.db_update_modules'][0] 	= 'Database update & migration scripts';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['installation.db_update_modules'][1] 	= 'The database is being updated with module information and migration scripts.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['installation.sql_template_import'][0]	= 'Executing installation template import...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['installation.sql_template_import'][1]	= 'Installing the SQL installation template of the demo data';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['installation.sql_template_wait'][0] 	= 'Importing installation template...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['installation.sql_template_wait'][1] 	= 'Importing installation template...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['manual_adjustment'][0] 					= 'Manual adjustments';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['manual_adjustment'][1] 					= 'Guide for manual adjustments.';

/**
 * Status
 */
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['welcome'] = '';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['validation'] = 'License query';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['accepted'] = 'License valid';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['not_accepted'] = 'License not valid';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['not_supported'] = 'This product is not supported.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['choose_product'] = 'Choose product...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['loading'] = 'Loading data';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['session_lost'] = 'License session expired';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['installation.unzip'] = 'Unzipping data';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['installation.copy_files'] = 'Copying data';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['installation.clear_cache'] = 'Clear prod. cache';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['installation.db_update_modules'] = 'Database update';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['manual_adjustment'] = 'Manual adjustments';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['done'] = 'Completed';

/**
 * Ajax infotexts
 */
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['AJAX_INFO']['validation'] = 'Requesting license...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['AJAX_INFO']['loading'] = 'File "%s" is being loaded...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['AJAX_INFO']['sql_template_import'] = 'Installation template is being imported...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['AJAX_INFO']['clear_cache'] = 'Cache is being cleared...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['AJAX_INFO']['copy_files'] = 'Files are being copied...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['AJAX_INFO']['unzip'] = 'Files are being unzipped...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['AJAX_INFO']['db_update_modules'] = 'Database is being updated...';


/**
 * Backend descriptions
 */
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['welcome'] 							= 'Welcome to the Theme Updater ('.\PCT_THEME_UPDATER.')';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['theme_updater_desc'] 				= 'The Theme Updater allows you to update the theme including all modules. All customizations made through the ThemeDesigner, as well as in customize.css/js and in the templates/ folder, will be retained. For a Contao update, we recommend our <a href="https://www.premium-contao-themes.com/contao-installer.html" target="_blank">Contao Installer.</a>';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['ready'] 								= 'Update: <span class="italic">%s</span>';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['loading'] 							= 'Loading data...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['choose_product'] 					= 'Your license includes more than one product.<br>Please select the product to install.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['error'] 								= 'Errors have occurred.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['file_not_exists'] 					= 'File no longer exists';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['access_denied'] 						= 'The license could not be validated.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['not_supported'] 						= 'The selected product is not supported.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['session_lost'] 						= 'The license session has expired. Please restart the installation.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['installation.unzip'] 				= 'Unzipping the data zip...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['installation.copy_files'] 			= 'The files are being copied to their destination...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['installation.clear_cache'] 			= 'Cache is being created with the new information.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['installation.db_update_modules'] 		= 'The database is being updated with the module information.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['installation.sql_template_wait'] 	= 'The demo website (installation template) is ready to be installed.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['installation.sql_template_import'] 	= 'The installation template is being imported.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['version_conflict'] 					= 'Version conflict';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['manual_adjustment'] 					= 'Manual adjustments';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['done'] 								= 'Summary';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['agreement'] 							= 'I have created a current backup of all relevant data, with which I can restore the website if necessary. All theme files (except for templates/, customize.css/js, ThemeDesigner adjustments) will be overwritten. An update in a live environment is not recommended. Seamedia® Themes accepts no liability or warranties for updates. (*Required field)';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['delete_demo_files']					= 'Delete demo files: Clears the folders /templates/demo_installer, files/cto_layout/img/delete_this upon completion of the update<p>Note: The data is required for the use of the demo installer.</p>';

/**
 * Categories
 */
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['CATEGORIES']['fe_modules'] = 'Frontend modules';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['CATEGORIES']['layout'] = 'Page layouts';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['CATEGORIES']['various'] = 'Other changes';
