<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2024
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_maintenance']['pct_themeupdater']['jobs'] 		= 'Theme-Updater tasks';
$GLOBALS['TL_LANG']['tl_maintenance']['pct_themeupdater']['run_job'] 		= 'Start';
$GLOBALS['TL_LANG']['tl_maintenance']['pct_themeupdater']['jobs_done']		= 'Task(s) [%s] completed';

/**
 * Jobs
 */
$GLOBALS['TL_LANG']['tl_maintenance']['pct_themeupdater']['news_order'][0] 				= 'Newslist sorting';
$GLOBALS['TL_LANG']['tl_maintenance']['pct_themeupdater']['news_order'][1] 				= 'Change newslist sorting from "date DESC" (unknown option) to "order_date_desc"';
$GLOBALS['TL_LANG']['tl_maintenance']['pct_themeupdater']['center_center_to_crop'][0] 	= 'Update image size selections';
$GLOBALS['TL_LANG']['tl_maintenance']['pct_themeupdater']['center_center_to_crop'][1] 	= 'Update image size seelctions from "CENTER_CENTER" (unknown option) to "CROP" ';
